name: Deploy to Kubernetes

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Configure kubectl
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 --decode > ${HOME}/.kube/config

    - name: Deploy to K8s
      run: kubectl apply -f full-php-app.yaml